[package]
name = "rust_dijkstra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rstest = "0.15.0"
assert_cmd = "2.0"
predicates = "2.1"
log = "0.4.17"
env_logger="0.9.3"
